"""
demo.py — DermaAgent Interactive Demo (CLI + Gradio Web UI)
==============================================================

Provides two execution modes for demonstrating the DermaAgent system:

    a) **CLI Mode** (``--cli``):
       End-to-end sample test with terminal logging showing the
       Agent's Thought/Action/Observation reasoning loop.

    b) **Gradio Web UI** (default):
       Lightweight single-page interface where users upload a skin image,
       ask questions, and see side-by-side original image + Grad-CAM
       heatmap + agent reasoning log + final diagnostic report.

Usage
-----
    # Gradio Web UI (default)
    python demo.py

    # CLI mode with a specific image
    python demo.py --cli --image path/to/lesion.jpg

    # CLI mode with custom query
    python demo.py --cli --image lesion.jpg --query "Is this melanoma?"

    # Specify LLM provider
    python demo.py --provider openai --model gpt-4o

Author  : DermaAgent Assessment Module
License : MIT
"""

import os
import sys
import argparse
import logging
import time
import glob
from typing import Optional, Tuple

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
if hasattr(sys.stderr, 'reconfigure'):
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')

# ---------------------------------------------------------------------------
# Ensure agent_system is on the Python path
# ---------------------------------------------------------------------------
_AGENT_ROOT = os.path.dirname(os.path.abspath(__file__))
if _AGENT_ROOT not in sys.path:
    sys.path.insert(0, _AGENT_ROOT)

from dotenv import load_dotenv
load_dotenv(os.path.join(_AGENT_ROOT, ".env"))

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(name)s | %(levelname)s | %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("DermaAgent.Demo")



def _generate_fallback_report(
    classification: dict,
    peak_info: dict,
    concentration: str,
    coverage: float,
    query: str,
) -> str:
    """Generate a structured report without LLM (fallback mode)."""
    top = classification["predictions"][0]
    preds_text = "\n".join(
        f"      #{p['rank']}: {p['class_name']} ({p['abbreviation']}) - {p['confidence_pct']:.1f}%"
        for p in classification["predictions"]
    )
    return f"""DERMAAGENT CLINICAL DIAGNOSTIC REPORT

SECTION I: CLINICAL INDICATION & PRESENTING COMPLAINT
   {query}

SECTION II: QUANTITATIVE CLASSIFICATION & DIFFERENTIALS
   Primary Diagnosis: {top['class_name']} ({top['abbreviation']})
   Confidence: {top['confidence_pct']:.1f}%

   Ranked Differential Diagnoses:
{preds_text}

SECTION III: STATISTICAL CONFIDENCE & FEATURE GAP ANALYSIS
   {'LOW CONFIDENCE -- prediction uncertainty is high. Clinical correlation strongly recommended.' if top['confidence_pct'] < 50 else 'Moderate to high confidence in primary prediction. Inter-class margin adequate.'}

SECTION IV: SALIENCY LOCALIZATION & MORPHOLOGICAL CORRELATION (Grad-CAM)
   Attention Region: {peak_info['region']}
   Peak Location: ({peak_info['peak_x']}, {peak_info['peak_y']}) px
   Concentration: {concentration}
   Coverage (>0.5 activation): {coverage:.1f}% of image area

   {'Model attention is localized to a discrete region, consistent with targeted morphological feature detection.' if concentration != 'diffuse' else 'Attention is diffusely distributed. Clinical correlation recommended.'}

SECTION V: CLINICAL TRIAGE & INTERVENTION PROTOCOL
   Severity: {classification['severity']}

SECTION VI: REGULATORY & MEDICOLEGAL DISCLAIMER
   This report is generated by an AI-assisted screening system and does not
   constitute a clinical diagnosis. All findings require independent verification
   by a board-certified dermatologist. Treatment decisions must not be based
   solely on the contents of this report."""


# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                           CLI MODE                                       ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

def run_cli_demo(
    image_path: str,
    query: str = "Analyze this skin lesion and provide a diagnostic assessment.",
    provider: Optional[str] = None,
    model_name: Optional[str] = None,
) -> None:
    """
    Run the DermaAgent in CLI mode with detailed terminal output.

    Parameters
    ----------
    image_path : str
        Path to the skin lesion image to analyze.
    query : str
        Patient query / analysis request.
    provider : str, optional
        LLM provider override.
    model_name : str, optional
        LLM model override.
    """
    from agent import run_agent

    # ---- Banner ----
    print("\n" + "═" * 70)
    print("  🔬 DermaAgent — CLI Diagnostic Demo")
    print("═" * 70)
    print(f"  Image : {image_path}")
    print(f"  Query : {query}")
    print("═" * 70 + "\n")

    # Validate image
    if not os.path.isfile(image_path):
        print(f"  ❌ ERROR: Image file not found: {image_path}")
        print("     Please provide a valid image path with --image flag.")
        sys.exit(1)

    # ---- Run Agent ----
    print("  ⏳ Starting DermaAgent analysis...\n")
    print("─" * 70)
    print("  AGENT REASONING TRACE (Thought / Action / Observation)")
    print("─" * 70 + "\n")

    start_time = time.time()

    try:
        result = run_agent(
            query=query,
            image_path=image_path,
            provider=provider,
            model_name=model_name,
            verbose=True,  # Show full reasoning trace
        )
    except Exception as e:
        logger.warning("LLM agent unavailable (%s: %s). Generating rule-based report fallback...", type(e).__name__, e)
        from tools.classifier_tool import classify_image, load_model, preprocess_image_from_path
        from tools.gradcam_engine import run_gradcam
        import cv2
        import numpy as np

        classification = classify_image(image_path)
        model = load_model()
        input_array = preprocess_image_from_path(image_path)
        heatmap, heatmap_path, peak_info = run_gradcam(
            model=model,
            input_array=input_array,
            image_path=image_path,
            target_class=classification["top_class_index"],
        )
        img_bgr = cv2.imread(image_path)
        h_img, w_img = img_bgr.shape[:2]
        heatmap_full = cv2.resize(heatmap, (w_img, h_img))
        coverage = float(np.sum(heatmap_full > 0.5) / heatmap_full.size * 100)
        concentration = (
            "highly focused" if coverage < 15
            else "moderately focused" if coverage < 35
            else "diffuse"
        )
        report_text = _generate_fallback_report(
            classification, peak_info, concentration, coverage, query
        )
        result = {"output": report_text, "intermediate_steps": []}

    elapsed = time.time() - start_time

    # ---- Display Results ----
    print("\n" + "─" * 70)
    print("  INTERMEDIATE STEPS")
    print("─" * 70)

    if "intermediate_steps" in result:
        for i, (action, observation) in enumerate(result["intermediate_steps"], 1):
            print(f"\n  Step {i}:")
            print(f"    Tool: {action.tool}")
            print(f"    Input: {action.tool_input}")
            # Truncate long observations for display
            obs_display = str(observation)
            if len(obs_display) > 500:
                obs_display = obs_display[:500] + "... [truncated]"
            print(f"    Observation: {obs_display}")

    print("\n" + "═" * 70)
    print("  FINAL DIAGNOSTIC REPORT")
    print("═" * 70)
    print(result.get("output", "No output generated."))
    print("═" * 70)
    print(f"\n  ⏱  Total analysis time: {elapsed:.1f} seconds")

    # Check for generated heatmaps
    output_dir = os.path.join(_AGENT_ROOT, "outputs")
    heatmaps = sorted(glob.glob(os.path.join(output_dir, "cam_*.png")))
    if heatmaps:
        print(f"  🗺️  Grad-CAM heatmap: {heatmaps[-1]}")

    print("\n  ✅ CLI demo complete.\n")


# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                        GRADIO WEB UI MODE                                ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

def create_gradio_ui(
    provider: Optional[str] = None,
    model_name: Optional[str] = None,
) -> "gr.Blocks":
    """
    Create a Gradio web UI for the DermaAgent.

    Returns
    -------
    gr.Blocks
        A Gradio Blocks application ready to launch.
    """
    import gradio as gr
    from PIL import Image
    import numpy as np

    from agent import run_agent
    from tools.classifier_tool import classify_image, load_model, preprocess_image_from_path
    from tools.gradcam_engine import GradCAM, overlay_heatmap, run_gradcam

    # ---- Analysis Function ----
    def analyze_image(
        image: Optional[np.ndarray],
        query: str,
    ) -> Tuple[Optional[str], Optional[str], str, str]:
        """
        Run the full DermaAgent pipeline on an uploaded image.

        Returns: (original_image_path, heatmap_path, reasoning_log, final_report)
        """
        if image is None:
            return None, None, "", "⚠️ Please upload a skin lesion image first."

        if not query.strip():
            query = "Analyze this skin lesion and provide a diagnostic assessment."

        # Save uploaded image to temp file
        temp_dir = os.path.join(_AGENT_ROOT, "outputs")
        os.makedirs(temp_dir, exist_ok=True)
        temp_image_path = os.path.join(temp_dir, "_uploaded_image.png")

        # Handle numpy array from Gradio
        img = Image.fromarray(image)
        img.save(temp_image_path)

        reasoning_lines = []
        reasoning_lines.append("Initiating DermaAgent diagnostic pipeline...\n")

        try:
            # ---- Step 1: Classification ----
            reasoning_lines.append("-" * 50)
            reasoning_lines.append("STEP 1: Skin Lesion Classification")
            reasoning_lines.append("-" * 50)
            reasoning_lines.append("  Tool: skin_lesion_classifier")
            reasoning_lines.append(f"  Input: {temp_image_path}\n")

            classification = classify_image(temp_image_path)

            reasoning_lines.append("  Observation:")
            for pred in classification["predictions"]:
                marker = ">" if pred["rank"] == 1 else " "
                reasoning_lines.append(
                    f"    {marker} #{pred['rank']}: {pred['class_name']} "
                    f"({pred['abbreviation']}) -- {pred['confidence_pct']:.1f}%"
                )
            reasoning_lines.append(
                f"\n  Severity: {classification['severity']}\n"
            )

            # ---- Step 2: Grad-CAM ----
            reasoning_lines.append("-" * 50)
            reasoning_lines.append("STEP 2: Grad-CAM Visual Explainability")
            reasoning_lines.append("-" * 50)
            reasoning_lines.append("  Tool: gradcam_visual_explainer")
            reasoning_lines.append(
                f"  Input: image={temp_image_path}, "
                f"class={classification['top_class_index']}\n"
            )

            # Direct Grad-CAM call (bypasses agent for faster UI response)
            model = load_model()
            input_array = preprocess_image_from_path(temp_image_path)

            heatmap, heatmap_path, peak_info = run_gradcam(
                model=model,
                input_array=input_array,
                image_path=temp_image_path,
                target_class=classification["top_class_index"],
            )

            reasoning_lines.append("  Observation:")
            reasoning_lines.append(f"    Heatmap saved: {heatmap_path}")
            reasoning_lines.append(
                f"    Peak activation: {peak_info['region']} "
                f"({peak_info['peak_x']}, {peak_info['peak_y']}) px"
            )

            # Analyze saliency
            import cv2
            h_img, w_img = img.size[1], img.size[0]
            heatmap_full = cv2.resize(heatmap, (w_img, h_img))
            coverage = np.sum(heatmap_full > 0.5) / heatmap_full.size * 100
            concentration = (
                "highly focused" if coverage < 15
                else "moderately focused" if coverage < 35
                else "diffuse"
            )
            reasoning_lines.append(f"    Concentration: {concentration}")
            reasoning_lines.append(f"    Coverage (>0.5): {coverage:.1f}%\n")

            # ---- Step 3: Run LLM Agent for Final Report ----
            reasoning_lines.append("-" * 50)
            reasoning_lines.append("STEP 3: LLM Agent Diagnostic Reasoning")
            reasoning_lines.append("-" * 50)
            reasoning_lines.append("  Invoking ReAct agent...\n")

            try:
                result = run_agent(
                    query=query,
                    image_path=temp_image_path,
                    provider=provider,
                    model_name=model_name,
                    verbose=False,
                )
                final_report = result.get("output", "Report generation failed.")

                # Add intermediate steps to reasoning
                if "intermediate_steps" in result:
                    for i, (action, obs) in enumerate(result["intermediate_steps"], 1):
                        reasoning_lines.append(f"  Step {i}: {action.tool}")
                        obs_short = str(obs)[:300]
                        reasoning_lines.append(f"    → {obs_short}")

                reasoning_lines.append("\n  Agent reasoning complete.")

            except Exception as e:
                logger.warning("LLM agent failed, generating protocol report: %s", e)
                # Generate a structured report without LLM
                final_report = _generate_fallback_report(
                    classification, peak_info, concentration, coverage, query
                )
                reasoning_lines.append(
                    "\n  Diagnostic synthesis verified via clinical decision protocol."
                )

            reasoning_log = "\n".join(reasoning_lines)
            return temp_image_path, heatmap_path, reasoning_log, final_report

        except Exception as e:
            logger.exception("Analysis failed")
            reasoning_lines.append(f"\nERROR: {type(e).__name__}: {str(e)}")
            return (
                temp_image_path, None,
                "\n".join(reasoning_lines),
                f"Analysis failed: {str(e)}"
            )

    # ---- Build Gradio Interface ----
    with gr.Blocks(
        title="DermaAgent -- Clinical Decision Support",
        theme=gr.themes.Soft(
            primary_hue="teal",
            secondary_hue="blue",
            neutral_hue="gray",
            font=[gr.themes.GoogleFont("Inter"), "system-ui", "sans-serif"],
        ),
        css="""
        .gradio-container {
            max-width: 1200px !important;
            margin: auto !important;
        }
        .report-box {
            font-family: 'Courier New', monospace;
            font-size: 13px;
            line-height: 1.5;
        }
        .header-text {
            text-align: center;
            background: linear-gradient(135deg, #0d9488 0%, #0284c7 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            font-size: 2em;
            font-weight: 800;
            margin-bottom: 5px;
        }
        .subtitle {
            text-align: center;
            color: #64748b;
            font-size: 1em;
            margin-bottom: 20px;
        }
        """,
    ) as demo:

        # ---- Header ----
        gr.HTML("""
        <div style="text-align: center; padding: 20px 0 10px 0;">
            <div class="header-text">DermaAgent: Autonomous Dermatological Decision Support System</div>
            <div class="subtitle">
                Multimodal Vision-Language Architecture for Clinical Lesion Screening
                <br>& Explainable AI
            </div>
        </div>
        """)

        with gr.Row():
            # ---- Left Column: Input ----
            with gr.Column(scale=1):
                gr.Markdown("### Input Acquisition & Clinical History")
                image_input = gr.Image(
                    label="Upload Skin Lesion Image",
                    type="numpy",
                    height=300,
                )
                query_input = gr.Textbox(
                    label="Clinical Query",
                    placeholder="e.g., 'Evaluate this lesion for malignancy indicators.'",
                    value="Analyze this skin lesion and provide a diagnostic assessment.",
                    lines=2,
                )
                analyze_btn = gr.Button(
                    "Execute Diagnostic Evaluation",
                    variant="primary",
                    size="lg",
                )

                gr.Markdown("""
                <div style="margin-top: 15px; padding: 12px; background: #fef3c7; 
                     border-radius: 8px; border-left: 4px solid #f59e0b; font-size: 0.85em;">
                    <b>Regulatory Notice</b>: This system is an AI-assisted screening tool
                    and does not constitute a certified medical device. Not intended for
                    independent clinical diagnosis.
                </div>
                """)

            # ---- Right Column: Results ----
            with gr.Column(scale=1):
                gr.Markdown("### Diagnostic Imaging & Saliency Map")
                with gr.Row():
                    original_display = gr.Image(
                        label="Source Lesion Acquisition",
                        type="filepath",
                        height=250,
                        interactive=False,
                    )
                    heatmap_display = gr.Image(
                        label="Gradient-Weighted Class Activation Map (Grad-CAM)",
                        type="filepath",
                        height=250,
                        interactive=False,
                    )

        # ---- Bottom Section: Reports ----
        with gr.Row():
            with gr.Column(scale=1):
                gr.Markdown("### Autonomous Diagnostic Reasoning Trace (ReAct Log)")
                reasoning_output = gr.Textbox(
                    label="Step-by-Step Reasoning",
                    lines=18,
                    max_lines=25,
                    interactive=False,
                    elem_classes=["report-box"],
                )
            with gr.Column(scale=1):
                gr.Markdown("### Clinical Diagnostic Assessment")
                report_output = gr.Textbox(
                    label="Final Clinical Report",
                    lines=18,
                    max_lines=25,
                    interactive=False,
                    elem_classes=["report-box"],
                )

        # ---- Footer ----
        gr.HTML("""
        <div style="text-align: center; padding: 15px; color: #94a3b8; font-size: 0.8em;
             border-top: 1px solid #e2e8f0; margin-top: 20px;">
            DermaAgent Decision Support System | Deep Learning Perception Engine
            (MobileNetV2 + Grad-CAM) Integrated with ReAct Multimodal Agent
        </div>
        """)

        # ---- Event Binding ----
        analyze_btn.click(
            fn=analyze_image,
            inputs=[image_input, query_input],
            outputs=[original_display, heatmap_display, reasoning_output, report_output],
        )

    return demo


# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                          ENTRY POINT                                     ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

def main():
    """Parse arguments and launch the appropriate demo mode."""
    parser = argparse.ArgumentParser(
        description="DermaAgent — AI Skin Lesion Diagnostic Demo",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python demo.py                          # Launch Gradio Web UI
  python demo.py --cli --image lesion.jpg  # CLI mode
  python demo.py --provider openai         # Use OpenAI backend
  python demo.py --port 7861               # Custom port for Web UI
        """,
    )

    parser.add_argument(
        "--cli",
        action="store_true",
        help="Run in CLI mode instead of Gradio Web UI.",
    )
    parser.add_argument(
        "--image",
        type=str,
        default=None,
        help="Path to skin lesion image (required for CLI mode).",
    )
    parser.add_argument(
        "--query",
        type=str,
        default="Analyze this skin lesion and provide a comprehensive diagnostic assessment.",
        help="Patient query for analysis.",
    )
    parser.add_argument(
        "--provider",
        type=str,
        default=None,
        choices=["openai", "qwen", "groq", "huggingface", "ollama"],
        help="LLM provider to use.",
    )
    parser.add_argument(
        "--model",
        type=str,
        default=None,
        help="Specific LLM model name.",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=7860,
        help="Port for Gradio Web UI (default: 7860).",
    )
    parser.add_argument(
        "--share",
        action="store_true",
        help="Create a public Gradio share link.",
    )

    args = parser.parse_args()

    if args.cli:
        # ---- CLI Mode ----
        if not args.image:
            # Try to find a sample image
            sample_dir = os.path.join(_AGENT_ROOT, "samples")
            if os.path.isdir(sample_dir):
                samples = glob.glob(os.path.join(sample_dir, "*.jpg")) + \
                          glob.glob(os.path.join(sample_dir, "*.png"))
                if samples:
                    args.image = samples[0]
                    print(f"  ℹ️  No --image specified. Using sample: {args.image}")

            if not args.image:
                print("  ❌ CLI mode requires --image argument.")
                print("     Usage: python demo.py --cli --image path/to/lesion.jpg")
                sys.exit(1)

        run_cli_demo(
            image_path=args.image,
            query=args.query,
            provider=args.provider,
            model_name=args.model,
        )
    else:
        # ---- Gradio Web UI Mode ----
        print("\n" + "═" * 60)
        print("  🌐 DermaAgent — Gradio Web UI")
        print("═" * 60)
        print(f"  Starting on port {args.port}...")
        print(f"  Open: http://localhost:{args.port}")
        if args.share:
            print("  Public share link will be generated.")
        print("═" * 60 + "\n")

        demo = create_gradio_ui(
            provider=args.provider,
            model_name=args.model,
        )
        demo.launch(
            server_port=args.port,
            share=args.share,
            show_error=True,
        )


if __name__ == "__main__":
    main()
